### ISSUE TITLE
SSL in development

### ISSUE THREAD

**Issue by ericsullivan** [tanguilp/wax_demo#2]
the webauthn seems to require SSL, which made testing this locally a tiny bit trickier. Thankfully, phoenix can generate SSL certificates `mix phx.gen.cert`. It just requires a small config change (see SSL Support in `config/dev.exs`). Did you want to me to commit that change (and the certificates) as a PR?

**Comment by tanguilp** [comment]
WebAuthn requires SSL, except when running or localhost :) So if the demo didn't work for you on localhost:4000 then please report as it means there is another problem

**Comment by ericsullivan** [comment]
I didn't know about localhost. I was using 127.0.0.1 and getting `DOMException: "The operation is insecure."`

**Comment by tanguilp** [comment]
That's the error you get when you don't use SSL indeed. Closing the issue since it's written explicitely to browse localhost in the README.
