### ISSUE TITLE
Ecto Integration

### ISSUE THREAD

**Issue by ericsullivan** [tanguilp/wax_demo#3]
I wanted to store the user cose keys in the DB. It wasn't too tricky, but I would have preferred and example or a note in the readme. Do you have a preference?

```
defmodule UserCoseKey do
  use Ecto.Schema

  schema "user_cose_keys" do
    field :raw_id, :string
    field :cose_key, CoseKeyType

    belongs_to :user, User

    timestamps()
  end
end

defmodule CoseKeyType do
  @behaviour Ecto.Type
  def type, do: :binary

  def load(data) do
    {:ok, :cbor.decode(data)}
  end

  def cast(data) do
    {:ok, data}
  end

  def dump(data) do
    {:ok, :cbor.encode(data) |> :erlang.iolist_to_binary()}
  end
end
```

**Comment by tanguilp** [comment]
I have absolutely no knowledge of Ecto :)
Why storing it as a CBOR binary, and not for instance JSONB?
Why not using http://erlang.org/doc/man/erlang.html#term_to_binary-1 instead of the CBOR function?

**Comment by ericsullivan** [comment]
I didn't know about `term_to_binary`, that's cool. That's why I was hoping to add some guidance :) I used cbor because that's what your library used and their [readme](https://github.com/yjh0502/cbor-erlang#encoder-mappings) suggested `iolist_to_binary`

**Comment by tanguilp** [comment]
Yeah CBOR doesn't directly encode to binary but to iolist because it's faster to put it on the wire. I think `term_to_binary` is the way to go. I'll add it. Since a user can have several credential_id it totally makes sense to create a SQL table.

**Comment by tanguilp** [comment]
Solved by https://github.com/tanguilp/wax/commit/9286133a4665d709f3590b37008f7beb570f65c2
